[project]
name = "llm_magnet"
version = "0.1.2"
description = "the small distributed language model toolkit. fine-tune state-of-the-art LLMs anywhere, rapidly."
readme = "dynamic"

[tool.setuptools.packages.find]
exclude = ["raw", "data"]